# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.3

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.3.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.3.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/hobu/dev/git/partio

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/hobu/dev/git/partio

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.3.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/Cellar/cmake/3.3.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local

.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hobu/dev/git/partio/CMakeFiles /Users/hobu/dev/git/partio/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/hobu/dev/git/partio/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named partio

# Build rule for target.
partio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partio
.PHONY : partio

# fast build rule for target.
partio/fast:
	$(MAKE) -f src/lib/CMakeFiles/partio.dir/build.make src/lib/CMakeFiles/partio.dir/build
.PHONY : partio/fast

#=============================================================================
# Target rules for targets named partattr

# Build rule for target.
partattr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partattr
.PHONY : partattr

# fast build rule for target.
partattr/fast:
	$(MAKE) -f src/tools/CMakeFiles/partattr.dir/build.make src/tools/CMakeFiles/partattr.dir/build
.PHONY : partattr/fast

#=============================================================================
# Target rules for targets named partconv

# Build rule for target.
partconv: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partconv
.PHONY : partconv

# fast build rule for target.
partconv/fast:
	$(MAKE) -f src/tools/CMakeFiles/partconv.dir/build.make src/tools/CMakeFiles/partconv.dir/build
.PHONY : partconv/fast

#=============================================================================
# Target rules for targets named partinfo

# Build rule for target.
partinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partinfo
.PHONY : partinfo

# fast build rule for target.
partinfo/fast:
	$(MAKE) -f src/tools/CMakeFiles/partinfo.dir/build.make src/tools/CMakeFiles/partinfo.dir/build
.PHONY : partinfo/fast

#=============================================================================
# Target rules for targets named partview

# Build rule for target.
partview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 partview
.PHONY : partview

# fast build rule for target.
partview/fast:
	$(MAKE) -f src/tools/CMakeFiles/partview.dir/build.make src/tools/CMakeFiles/partview.dir/build
.PHONY : partview/fast

#=============================================================================
# Target rules for targets named makecircle

# Build rule for target.
makecircle: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 makecircle
.PHONY : makecircle

# fast build rule for target.
makecircle/fast:
	$(MAKE) -f src/tests/CMakeFiles/makecircle.dir/build.make src/tests/CMakeFiles/makecircle.dir/build
.PHONY : makecircle/fast

#=============================================================================
# Target rules for targets named makeline

# Build rule for target.
makeline: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 makeline
.PHONY : makeline

# fast build rule for target.
makeline/fast:
	$(MAKE) -f src/tests/CMakeFiles/makeline.dir/build.make src/tests/CMakeFiles/makeline.dir/build
.PHONY : makeline/fast

#=============================================================================
# Target rules for targets named testcache

# Build rule for target.
testcache: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testcache
.PHONY : testcache

# fast build rule for target.
testcache/fast:
	$(MAKE) -f src/tests/CMakeFiles/testcache.dir/build.make src/tests/CMakeFiles/testcache.dir/build
.PHONY : testcache/fast

#=============================================================================
# Target rules for targets named testclonecopy

# Build rule for target.
testclonecopy: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testclonecopy
.PHONY : testclonecopy

# fast build rule for target.
testclonecopy/fast:
	$(MAKE) -f src/tests/CMakeFiles/testclonecopy.dir/build.make src/tests/CMakeFiles/testclonecopy.dir/build
.PHONY : testclonecopy/fast

#=============================================================================
# Target rules for targets named testiterator

# Build rule for target.
testiterator: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testiterator
.PHONY : testiterator

# fast build rule for target.
testiterator/fast:
	$(MAKE) -f src/tests/CMakeFiles/testiterator.dir/build.make src/tests/CMakeFiles/testiterator.dir/build
.PHONY : testiterator/fast

#=============================================================================
# Target rules for targets named testkdtree

# Build rule for target.
testkdtree: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testkdtree
.PHONY : testkdtree

# fast build rule for target.
testkdtree/fast:
	$(MAKE) -f src/tests/CMakeFiles/testkdtree.dir/build.make src/tests/CMakeFiles/testkdtree.dir/build
.PHONY : testkdtree/fast

#=============================================================================
# Target rules for targets named testpartio

# Build rule for target.
testpartio: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 testpartio
.PHONY : testpartio

# fast build rule for target.
testpartio/fast:
	$(MAKE) -f src/tests/CMakeFiles/testpartio.dir/build.make src/tests/CMakeFiles/testpartio.dir/build
.PHONY : testpartio/fast

#=============================================================================
# Target rules for targets named teststr

# Build rule for target.
teststr: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 teststr
.PHONY : teststr

# fast build rule for target.
teststr/fast:
	$(MAKE) -f src/tests/CMakeFiles/teststr.dir/build.make src/tests/CMakeFiles/teststr.dir/build
.PHONY : teststr/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f src/doc/CMakeFiles/doc.dir/build.make src/doc/CMakeFiles/doc.dir/build
.PHONY : doc/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... partio"
	@echo "... partattr"
	@echo "... partinfo"
	@echo "... partconv"
	@echo "... partview"
	@echo "... makecircle"
	@echo "... testkdtree"
	@echo "... testclonecopy"
	@echo "... makeline"
	@echo "... testiterator"
	@echo "... testcache"
	@echo "... teststr"
	@echo "... testpartio"
	@echo "... doc"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

